const LANGUAGE_STORAGE_KEY = 'guitar-chords-library-language';

const TRANSLATIONS = {
    en: {
        language: 'Language', libraryTitle: 'Guitar Chords Library', librarySubtitle: 'All the chords you need, at your fingertips',
        identifierTitle: 'Chord Identifier', identifierSubtitle: 'Click on the fretboard to select notes and find the chord',
        circleTitle: 'Circle of Fifths', circleSubtitle: 'Explore keys, modes, and chord relationships',
        chordLibrary: 'Chord Library', chordIdentifier: 'Chord Identifier', circleOfFifths: 'Circle of Fifths',
        all: 'All', pinned: 'Pinned', key: 'Key:', mode: 'Mode:', scaleNotes: 'Scale Notes', diatonicChords: 'Diatonic Chords', keyRelationships: 'Key Relationships',
        clearAll: 'Clear All', cancelPreview: 'Cancel Preview', selectedNotes: 'Selected Notes', identifiedChord: 'Identified Chord', noNotesSelected: 'No notes selected',
        instructions: 'How to use:', instruction1: 'Click on any fret position to add/remove a note', instruction2: 'Select at least 2 notes to identify a chord', instruction3: 'The chord is identified automatically as you select notes', instruction4: 'Click "Clear All" to start over',
        footer: 'Guitar Chords Library © 2026', disclaimer: 'This website was generated by AI. Information may contain errors or inaccuracies. Please verify independently before relying on any content.',
        shiftLeft: 'Shift chord left one fret', shiftRight: 'Shift chord right one fret', clickMore: 'Click for more shapes', noPinned: 'No pinned chords yet. Use the pin button on any chord diagram to add it here.',
        major: 'Major', minor: 'Minor', diminished: 'Diminished', augmented: 'Augmented', unknown: 'Unknown', notes: 'Notes', selectTwo: 'Select at least 2 notes to identify a chord', selectDifferent: 'Select different notes (currently only one pitch class)', noMatch: "This combination doesn't exactly match a standard chord.", suggestions: 'Suggested chords (hover to preview, click to pin):', otherPossibilities: 'Other possibilities (hover to preview, click to pin):', notesMatch: 'notes match', missing: 'missing',
        relativeMinor: 'Relative Minor:', relativeMajor: 'Relative Major:', dominant: 'Dominant (V):', subdominant: 'Subdominant (IV):', parallel: 'Parallel:', keySignature: 'Key Signature:', chordShape: 'Chord Shape', shapeUnavailable: 'Shape unavailable'
    },
    'zh-Hant': {
        language: '語言', libraryTitle: '吉他和弦庫', librarySubtitle: '所有需要的和弦，隨手可得', identifierTitle: '和弦辨識器', identifierSubtitle: '點擊指板選取音符並找出和弦', circleTitle: '五度圈', circleSubtitle: '探索調性、調式與和弦關係', chordLibrary: '和弦庫', chordIdentifier: '和弦辨識器', circleOfFifths: '五度圈', all: '全部', pinned: '已釘選', key: '調性：', mode: '調式：', scaleNotes: '音階音符', diatonicChords: '自然和弦', keyRelationships: '調性關係', clearAll: '清除全部', cancelPreview: '取消預覽', selectedNotes: '已選音符', identifiedChord: '辨識的和弦', noNotesSelected: '尚未選取音符', instructions: '使用方式：', instruction1: '點擊任一琴格以加入或移除音符', instruction2: '至少選取兩個音符來辨識和弦', instruction3: '選取音符時會自動辨識和弦', instruction4: '點擊「清除全部」重新開始', footer: '吉他和弦庫 © 2026', disclaimer: '本網站由 AI 產生。資訊可能有錯誤或不準確之處，請在使用前自行查證。', shiftLeft: '將和弦向左移一格', shiftRight: '將和弦向右移一格', clickMore: '點擊查看更多按法', noPinned: '尚未釘選和弦。使用任一和弦圖上的圖釘按鈕即可加入。', major: '大和弦', minor: '小和弦', diminished: '減和弦', augmented: '增和弦', unknown: '未知', notes: '音符', selectTwo: '至少選取兩個音符來辨識和弦', selectDifferent: '請選取不同音符（目前只有一個音高類別）', noMatch: '此組合並不完全符合標準和弦。', suggestions: '建議和弦（懸停預覽，點擊釘選）：', otherPossibilities: '其他可能性（懸停預覽，點擊釘選）：', notesMatch: '個音符符合', missing: '個缺少', relativeMinor: '關係小調：', relativeMajor: '關係大調：', dominant: '屬和弦 (V)：', subdominant: '下屬和弦 (IV)：', parallel: '同主調：', keySignature: '調號：', chordShape: '和弦指型', shapeUnavailable: '指型不可用'
    },
    'zh-Hans': {
        language: '语言', libraryTitle: '吉他和弦库', librarySubtitle: '所有需要的和弦，随手可得', identifierTitle: '和弦识别器', identifierSubtitle: '点击指板选择音符并找出和弦', circleTitle: '五度圈', circleSubtitle: '探索调性、调式与和弦关系', chordLibrary: '和弦库', chordIdentifier: '和弦识别器', circleOfFifths: '五度圈', all: '全部', pinned: '已置顶', key: '调性：', mode: '调式：', scaleNotes: '音阶音符', diatonicChords: '自然和弦', keyRelationships: '调性关系', clearAll: '清除全部', cancelPreview: '取消预览', selectedNotes: '已选音符', identifiedChord: '识别的和弦', noNotesSelected: '尚未选择音符', instructions: '使用方式：', instruction1: '点击任一琴格以添加或移除音符', instruction2: '至少选择两个音符来识别和弦', instruction3: '选择音符时会自动识别和弦', instruction4: '点击“清除全部”重新开始', footer: '吉他和弦库 © 2026', disclaimer: '本网站由 AI 生成。信息可能有错误或不准确之处，请在使用前自行核实。', shiftLeft: '将和弦向左移一格', shiftRight: '将和弦向右移一格', clickMore: '点击查看更多按法', noPinned: '尚未置顶和弦。使用任一和弦图上的图钉按钮即可添加。', major: '大和弦', minor: '小和弦', diminished: '减和弦', augmented: '增和弦', unknown: '未知', notes: '音符', selectTwo: '至少选择两个音符来识别和弦', selectDifferent: '请选择不同音符（当前只有一个音高类别）', noMatch: '此组合并不完全符合标准和弦。', suggestions: '建议和弦（悬停预览，点击置顶）：', otherPossibilities: '其他可能性（悬停预览，点击置顶）：', notesMatch: '个音符符合', missing: '个缺少', relativeMinor: '关系小调：', relativeMajor: '关系大调：', dominant: '属和弦 (V)：', subdominant: '下属和弦 (IV)：', parallel: '同主调：', keySignature: '调号：', chordShape: '和弦指型', shapeUnavailable: '指型不可用'
    }
};

Object.assign(TRANSLATIONS.en, {
    seventh: '7th', major7: 'Maj7', minor7: 'm7', dim: 'Dim', aug: 'Aug', sus2: 'Sus2', sus4: 'Sus4',
    ionian: 'Ionian', dorian: 'Dorian', phrygian: 'Phrygian', lydian: 'Lydian', mixolydian: 'Mixolydian', aeolian: 'Aeolian', locrian: 'Locrian', allShapes: 'All Shapes'
});
Object.assign(TRANSLATIONS['zh-Hant'], {
    seventh: '屬七', major7: '大七', minor7: '小七', dim: '減', aug: '增', sus2: '掛二', sus4: '掛四',
    ionian: '伊奧尼亞', dorian: '多利安', phrygian: '弗里幾亞', lydian: '利底亞', mixolydian: '混合利底亞', aeolian: '愛奧尼亞', locrian: '洛克里亞', allShapes: '所有指型'
});
Object.assign(TRANSLATIONS['zh-Hans'], {
    seventh: '属七', major7: '大七', minor7: '小七', dim: '减', aug: '增', sus2: '挂二', sus4: '挂四',
    ionian: '伊奥尼亚', dorian: '多利亚', phrygian: '弗里吉亚', lydian: '利底亚', mixolydian: '混合利底亚', aeolian: '爱奥尼亚', locrian: '洛克里亚', allShapes: '所有指型'
});

function getLanguage() {
    return localStorage.getItem(LANGUAGE_STORAGE_KEY) || 'en';
}

function t(key) {
    const language = getLanguage();
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
}

function applyTranslations() {
    const language = getLanguage();
    document.documentElement.lang = language;
    document.querySelectorAll('[data-i18n]').forEach(element => {
        element.textContent = t(element.dataset.i18n);
    });
    document.querySelectorAll('[data-i18n-title]').forEach(element => {
        element.title = t(element.dataset.i18nTitle);
        element.setAttribute('aria-label', t(element.dataset.i18nTitle));
    });
}

function createLanguageSelector() {
    const selector = document.createElement('select');
    selector.className = 'language-selector';
    selector.setAttribute('aria-label', t('language'));
    selector.innerHTML = '<option value="en">English</option><option value="zh-Hant">繁體中文</option><option value="zh-Hans">简体中文</option>';
    selector.value = getLanguage();
    selector.addEventListener('change', () => {
        localStorage.setItem(LANGUAGE_STORAGE_KEY, selector.value);
        applyTranslations();
        document.dispatchEvent(new Event('languagechange'));
    });
    document.body.appendChild(selector);
}

document.addEventListener('DOMContentLoaded', () => {
    applyTranslations();
    createLanguageSelector();
});
